server:
  port: 8881
spring:
  boot:
    admin:
      client:
        url: http://193.112.176.35:8900
        api-path: /instances
        instance:
          service-base-url: http://localhost:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS